import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar04 from '@/components/navbar-04/navbar-04';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar04 />
        {children}
      </body>
    </html>
  );
}
